INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Afonso Linhares',1);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Afonso Neiva',1);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Albino Serpa',1);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Alceste Moreno',1);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Alda Póvoas',1);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Alexandre Cruz',1);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Alice Filipe',1);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Almeno Foquiço',1);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Alvito Estrella',1);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Amandio Peralta',1);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Amélia León',1);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Anabela Queirós',1);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Antão Macieira',1);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Araci Ríos',1);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Arcidres Fitas',1);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Arcidres Querino',1);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Barnabé Nóbrega',2);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Bernardo Cambezes',2);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Brites Borges',2);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Brites Braga',2);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Bárbara Espargosa',2);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Capitolino Sabala',2);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Casimiro Bivar',2);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Casimiro Villas Boas',2);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Conceição Lousã',2);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Constança Pari',2);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Cosme Gomide',2);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Custódio Guedella',2);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Damião Sales',2);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Deise Zarco',2);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Denise Quintas',2);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Diamantino Rodríguez',2);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Dina Outeiro',3);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Dinis Malheiro',3);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Edmundo Zalazar',3);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Emanuela Capanema',3);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Emídio Rufino',3);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Epifânia Camarinho',3);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Ester Cachoeira',3);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Ester Rodovalho',3);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Florinda Zagallo',3);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Francisco Jordão',3);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Gabriela Nóbrega',3);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Germano Madruga',3);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Gina Alancastro',3);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Gláuber Malheiros',3);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Godo Flores',3);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Gualdim Thamily',3);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Gustavo Camarinho',4);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Hermano Assumpção',4);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Hermígio Passarinho',4);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Ilduara Rosa',4);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Inaiá Sabrosa',4);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Itiberê Luz',4);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Iva Benevides',4);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Ivo Espírito Santo',4);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Jacir Bethancout',4);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Josefina Flores',4);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('João Vicario',4);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Lopo Cantanhede',4);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Lopo Ribeiro',4);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Luciano Patrício',4);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Luzia Garcez',4);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Magali Outeiro',4);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Maiara Cirne',5);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Marisa Cabeça de Vaca',5);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Marta Infante',5);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Marília Silvestre',5);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Matilde Casado',5);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Miguel Hierro',5);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Murilo Saraíba',5);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Máximo Valentim',5);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Otávio Marques',5);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Penélope Zarco',5);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Priscila Olivares',5);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Quintiliano Grande',5);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Quitéria Cabral',5);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Ramão Britto',5);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Reinaldo Faia',5);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Rubim Silvestre',5);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Ruca Barateiro',6);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Rudi Varão',6);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Sabino Bugallo',6);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Sabino Lóio',6);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Sebastiana Sousa',6);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Silvano Carrasqueira',6);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Simão Porciúncula',6);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Susana Lagos',6);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Sílvio Porto',6);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Sónia Garcés',6);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Sônia ou Sonia Castilho',6);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Ubaldo Passos',6);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Ubiratã Grangeia',6);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Valdemar Estrela',6);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Vicente Machado',6);
INSERT INTO aluno (aluno_nome,turma_id) VALUES ('Vlademiro Ourique',6);
INSERT INTO aluno (aluno_nome) VALUES ('Vlademiro Pavía');
INSERT INTO aluno (aluno_nome) VALUES ('Zubaida Carvalheiro');
INSERT INTO aluno (aluno_nome) VALUES ('Álvaro Novaes');
INSERT INTO aluno (aluno_nome) VALUES ('Élvio Tristão');


INSERT INTO turma (turma_nome) VALUES ("TurmaA");
INSERT INTO turma (turma_nome) VALUES ("TurmaB");
INSERT INTO turma (turma_nome) VALUES ("TurmaC");
INSERT INTO turma (turma_nome) VALUES ("TurmaD");
INSERT INTO turma (turma_nome) VALUES ("TurmaE");
INSERT INTO turma (turma_nome) VALUES ("TurmaF");
INSERT INTO turma (turma_nome) VALUES ("TurmaG");
INSERT INTO turma (turma_nome) VALUES ("TurmaH");
INSERT INTO turma (turma_nome) VALUES ("TurmaI");
INSERT INTO turma (turma_nome) VALUES ("TurmaJ");
INSERT INTO turma (turma_nome) VALUES ("TurmaK");
INSERT INTO turma (turma_nome) VALUES ("TurmaL");
INSERT INTO turma (turma_nome) VALUES ("TurmaM");